### ISSUE TITLE
Does hashcode matter?

### ISSUE THREAD

**Issue by h-unterp** [quantosapplications/riverpod_infinite_scroll#10]
Shouldn't this example of custom state have an == method for it to operate in a list properly? sort/find etc?

https://github.com/quantosapplications/riverpod_infinite_scroll/blob/710a4d939593a9114b99772d1225ef816cce8e19/example/lib/custom/custom_example_provider.dart#L12

**Comment by ftognetto** [comment]
Yes it should, you are right.
If we can make the class PagedState freezable (I'm referring to https://github.com/quantosapplications/riverpod_infinite_scroll/issues/8) we would have == and hashcode implementation directly from freezed.
Otherwise I will add an implementation

**Comment by ftognetto** [comment]
Hi i have added the equal, hashcode and toString method on PagedState.
Thank you!
