### ISSUE TITLE
Update Docs with List<String>? previousPageKeys

### ISSUE THREAD

**Issue by h-unterp** [quantosapplications/riverpod_infinite_scroll#11]
Custom example in docs https://github.com/quantosapplications/riverpod_infinite_scroll/blob/710a4d939593a9114b99772d1225ef816cce8e19/README.md?plain=1#L233

Needs to have 

List<String>? previousPageKeys

https://github.com/quantosapplications/riverpod_infinite_scroll/blob/710a4d939593a9114b99772d1225ef816cce8e19/example/lib/custom/custom_example_provider.dart#L21

**Comment by ftognetto** [comment]
Thank you, I have updated the docs!
