### ISSUE TITLE
pullToRefresh 'StateNotifierProvider<FeedStateNotifier, FeedState>' is not a subtype of type 'ProviderBase<Future<void>>')

### ISSUE THREAD

**Issue by h-unterp** [quantosapplications/riverpod_infinite_scroll#13]
I would like to try to fix this bug, but not sure why it is occurring. Any ideas?

Also, in my 1.0.4 from pub.dev error is on line 161, however github same line is 179. The github is ahead of pub.dev?

https://github.com/quantosapplications/riverpod_infinite_scroll/blob/710a4d939593a9114b99772d1225ef816cce8e19/lib/src/river_paged_builder.dart#L179
```
_TypeError (type 'StateNotifierProvider<FeedStateNotifier, FeedState>' is not a subtype of type 'ProviderBase<Future<void>>')
```
![Screen Shot 2022-06-27 at 12 12 38 AM](https://user-images.githubusercontent.com/772917/175858731-b1308cd5-bd67-4bf0-9370-6b48ae83759f.png)

**Comment by ftognetto** [comment]
There was a fix for that, Idk why it isn't present in 1.0.4
it should be 

```
if (widget.pullToRefresh) {
      pagedBuilder = RefreshIndicator(
          onRefresh: () async => ref.refresh(_provider), child: pagedBuilder);
    }
```
