### ISSUE TITLE
state is erased in pullToRefresh with PagedNotifierMixin

### ISSUE THREAD

**Issue by h-unterp** [quantosapplications/riverpod_infinite_scroll#17]
enable pull to refresh on custom example, then set a breakpoint: https://github.com/ftognetto/riverpod_infinite_scroll/blob/5d596555f653f201da086a7d775a3607e6df239b/example/lib/custom/custom_example_provider.dart#L63

You will see that all of the members of the state object are null. 

![Screen Shot 2022-07-16 at 1 37 16 PM](https://user-images.githubusercontent.com/772917/179366035-ad266c3c-1bff-41ae-b4a8-b9850948cc0b.png)

You may need to pull to refresh a few times.

However in my app, the state is "erased" after the first pullToRefresh

**Comment by h-unterp** [comment]
Maybe this is not a bug? Riverpod will dispose the provider when it is refreshed. The only issue is how to handle this properly. The example seems to work ok.

**Comment by ftognetto** [comment]
Hi @h-unterp sorry for the late reply I unfortunately broken my arms, and now I'm slowly coming back :)

What's the problem here? When you pull to refresh riverpod will refresh entirely your provider so it's normal that your state is empty at that point
