### ISSUE TITLE
any idea why my listtile always fetches before it reaches bottom of page? any way to change it?

### ISSUE THREAD

**Issue by HafizAlwi** [quantosapplications/riverpod_infinite_scroll#21]
is this the effect of infinite_scroll_pagination invisibleitemsthreshold? I kinda like how seamless it seems but I would like a way to only fetch the new page when I reach end of page? I am using pagedlistview.

**Comment by ftognetto** [comment]
Hi @HafizAlwi yes this is a feature that infinite_scroll_pagination already expose and it is called `invisibleItemsThreshold` and it means the number of remaining invisible items that should trigger a new fetch.
There is a default of 3 items, but I'm adding right now in riverpod_infinite_scroll's RiverPagedBuilder so you can change it as you need
