### ISSUE TITLE
Issue with nextPageKey: users.length < limit ? null : users[users.length - 1].id);

### ISSUE THREAD

**Issue by dyardy** [quantosapplications/riverpod_infinite_scroll#23]
I started with the custom example, and changed to use an api datasource.  The api returned back List<User> as well as total results.

I tried running as-is and the paging was never progressing beyond 1.
`nextPageKey: users.length < limit ? null : users[users.length - 1].id);`

It was not clear to me where the value of limit came from.
I realized that I needed to set limit = {api results maximum record count returned by the api call}

In addition the above nextPageKey also did not appear to be applicable.

I replaced with 
`nextPageKey: myPagination(users, page, limit));`

then added my myPagination function that looks like
```
  myPagination(List<dynamic>? lastItems, int  page, int  limit) {
    return (lastItems == null || lastItems.length < limit) ? (page + 1) : null;
  }
```

**Is this the right approach?** (as mentioned it was difficult for me to understand how paging and limits were coming from)

thx

**Comment by ftognetto** [comment]
Hi @dyardy this depends of the kind of paging that the api is using and also the kind of db that there is behind the api.
For a "mysql" pagination I wrote a custom function:

```
static NextPageKeyBuilder<int, dynamic> mysqlPagination =
      (List<dynamic>? lastItems, int page, int limit) {
    return (lastItems == null || lastItems.length < limit) ? null : (page + 1);
  };
```

But in your case it seems you are using a cursor based pagination (useful on mongodb for example).

In that case I would use something like 

`nextPageKey: entities.isNotEmpty ? entities[entities.length - 1].id : null`
