### ISSUE TITLE
Is it possible to use this within a CustomScrollView?

### ISSUE THREAD

**Issue by dJani97** [quantosapplications/riverpod_infinite_scroll#28]
I'm trying to build something like this:

```dart
@override
Widget build(BuildContext context, WidgetRef ref) {
  return Scaffold(
    body: CustomScrollView(
      slivers: [
        const SliverAppBar(
          title: Text('SliverAppBar'),
        ),
        RiverPagedBuilder<int, Item>(
          pullToRefresh: true,
          firstPageKey: 0,
          provider: itemProvider,
          itemBuilder: (context, item, index) => Text(item.name!),
          pagedBuilder: (controller, builder) =>
              PagedSliverList(pagingController: controller, builderDelegate: builder),
        )
      ],
    ),
  );
}
```

According to [this example](https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/example/lib/presentation/search_snackbar/character_sliver_list.dart), `infinite_scroll_pagination` supports such layouts. Can I achieve the same with `riverpod_infinite_scroll`?

**Comment by ftognetto** [comment]
Of course @dJani97 I'm using sliver in many situations.
The syntax is the same, your code seems fine to me.

**Comment by MartkCz** [comment]
@dJani97 `pullToRefresh` must be false and use `RefreshIndicator(CustomScrollView)` or use `NestedScrollView` instead.

The problem is here https://github.com/ftognetto/riverpod_infinite_scroll/blob/main/lib/src/river_paged_builder.dart#L187-L190 , refresh indicator cannot be used as sliver

**Comment by ftognetto** [comment]
Thanks @MartkCz I didn't noticed the `pullToRefresh: true`
