### ISSUE TITLE
How to force clear of cached items?

### ISSUE THREAD

**Issue by davoutuk** [quantosapplications/riverpod_infinite_scroll#32]
I have an issue with paged items being cached

In the taskListPagingProvider  I am have a ref.watch(taskCrudProvider)  that is meant to force a complete query rebuild and refresh

However, this is not happening.  It appears that the original data results are being cached and the new query is not being used.

```
 @override
  Widget build(BuildContext context) {

    final aPageSize = ref.watch(userPreferencesProvider.select((value) => value.listPageSize));
    final aTileConfig = ref.watch(taskDisplayProvider.select((value) => value.displayConfig.listView.tile));

    return RiverPagedBuilder<int,GdTask>(
      firstPageKey: 0,
      limit: aPageSize,
      provider: taskListPagingProvider,
      itemBuilder: (context,item,index) {
        return TaskTile(item,aTileConfig);
      },
      pagedBuilder: (controller,builder) => ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: TaskTileConfig.listMaxWidth),
          child: PagedListView(pagingController: controller,builderDelegate: builder))
    );
  }
```

```
final taskListPagingProvider = StateNotifierProvider<TaskListPagingNotifier,PagedState<int,GdTask>>( (ref)  {

  ref.watch(authenticationProvider);
  ref.watch(taskCrudProvider);   //  <== this is meant to force a re-query to refresh the page
  final aListConfig = ref.watch(taskDisplayProvider.select((value) => value.displayConfig.listView));
  final aTaskFilter = ref.watch(taskFilterProvider);

  FindParameters aParams = FindParameters();
  aParams.group = GdGroupDefUtil.copy(aListConfig.group);
  aParams.sort = GdSortDefUtil.copy(aListConfig.sort);
  aParams.search.appendSearch(aTaskFilter.search);

  return TaskListPagingNotifier(aParams,ref.watch(taskServiceProvider));
});
```

**Comment by ftognetto** [comment]
Hi! If you need to refresh the list you can wrap the RiverPagedBuilder in a RefreshIndicator like

```
RefreshIndicator(
      onRefresh: () async {
        return ref.refresh(taskListPagingProvider);
      },
      child: RiverPagedBuilder<int,GdTask>(
         ...
      )
)
```

Is this what you were trying to do?

**Comment by davoutuk** [comment]
The paged list is showing a filtered list of items.   The 'taskListPagingProvider ' is the source of that list. 
Any changes to items in the list (add, update, delete) are actioned by calling methods on the 'taskCrudProvider'.
To ensure that the list is showing the latest correct data,  a full refresh is required on 'taskListPagingProvider'. This is achieved by including a 'ref.watch( taskCrudProvider)' code inside the 'taskListPagingProvider'  function.

Hence, 
1).  taskListPagingProvider  is used to generate the list
2). any add/update/delete changes to items in the list are actioned on the 'taskCrudProvider'.
3).  Any add/update/delete to an item will force a change to the 'taskCrudProvider' state
4).  the change in 'taskCrudProvider' state will trigger a refresh of the taskListPagingProvider, because there is a 'ref.watch(taskCrudProvider' code line in the taskListPagingProvider function.

**Comment by ftognetto** [comment]
Ook that should work.
You are retrieving the items to display from taskDisplayProvider, is that provider also listening to taskCrudProvider?

**Comment by davoutuk** [comment]
It's not working
taskDisplayProvider is used to bring back some item display configuration, and has nothing to do with fetching data from the back end

One weird thing I've noticed:
The list is displayed to start with
I edit an entry in the list to change its display date
This date change will trigger the taskCrudProvider which in turn will cause the taskListPagingProvider to refresh
The new changed date is NOT displayed in the list - the old date remains
Now if I change the same item date again then after this second change the new date is shown in the list

**Comment by davoutuk** [comment]
I've found the issue - I was missing an 'await' prefix on the update data path which meant that the select was being executed before the update was completed.

**Comment by davoutuk** [comment]
My error
