### ISSUE TITLE
Adding a grouped display to a list?

### ISSUE THREAD

**Issue by davoutuk** [quantosapplications/riverpod_infinite_scroll#33]
Any suggestions for how I might add a grouped list display ?

An example is shown below...

![image](https://user-images.githubusercontent.com/25985256/233374744-70bd1aee-0e5f-425d-9d96-389bd9854c16.png)

The grouped data element would display as a distinct row in the display, with all related items displayed below it

**Comment by ftognetto** [comment]
Mm I think you could handle the group as the elements of the list and then in the renderItem function render the sublist.
Or else you should use Slivers.
For that you can follow the infinite_scroll_pagination documentation!

**Comment by davoutuk** [comment]
The idea is use ExpansionTile for the group title, and then have the child items set as children of the expansion tile

**Comment by ftognetto** [comment]
Yes it's perfectly fine to handle such a scenario with this package as long as the api you're calling is returning paginated groups with subelements.
Then on the ui you can use anything you want to render the su list even a simple column widget can help you for having a result like the image you shared
