### ISSUE TITLE
idea of an option that would make it possible not to refresh data when returning to the page where pagination is used

### ISSUE THREAD

**Issue by pmkod** [quantosapplications/riverpod_infinite_scroll#34]
when I use pagination on a page, when I leave it and return to it all the data is reloaded, you can implement a boolean option that will say whether or not you want the data to be reloaded. that would be really useful to me and to lots of other people.

**Comment by maxzod** [comment]
just removing `.autoDispose` would do what you need

**Comment by ftognetto** [comment]
If I understand correctly what you are trying to do I think you just need to use a stateful widget that implements `AutomaticKeepAliveClientMixin` with 
```
@override
bool get wantKeepAlive => true;
```
This way the page will not be reloaded

**Comment by pmkod** [comment]
I just did this but there's always a refresh.
