### ISSUE TITLE
Will this support AsyncNotifier as well?

### ISSUE THREAD

**Issue by sevenfold4** [quantosapplications/riverpod_infinite_scroll#38]
I was planning to use infinite scroll pagination with AsyncNotifer, however, it does not update the values, when AsyncNotifier gets updated. Will this work in its current state?

**Comment by ftognetto** [comment]
Check the https://github.com/ftognetto/riverpod_infinite_scroll/issues/36 too we will use it as a tracking issue for the new notifiers + generation
