### ISSUE TITLE
Support `infinite_scroll_pagination 4.0.0`

### ISSUE THREAD

**Issue by dJani97** [quantosapplications/riverpod_infinite_scroll#40]
`infinite_scroll_pagination 4.0.0` was just released a week ago, it would be great to get support for it in the long term.

**Comment by nader138** [comment]
I got an error trying to build for Flutter 3.22:

```
../.pub-cache/hosted/pub.dev/infinite_scroll_pagination-3.2.0/lib/src/ui/default_indicators/first_page_exception_indicator.dart:27:50: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../development/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
              style: Theme.of(context).textTheme.headline6,
```

@ftognetto `infinite_scroll_pagination 4.0.0` resolves this issue so its critical to support it! otherwise this package is no longer useful..

**Comment by nader138** [comment]
There seems to be a fork with a fix for that, it can be found here: https://github.com/acterglobal/riverpod_infinite_scroll

**Comment by ftognetto** [comment]
Hi this should be resolved in https://github.com/ftognetto/riverpod_infinite_scroll/pull/45

**Comment by nathanRamaNoodles** [comment]
@ftognetto
PR #45 doesn't seem to be in the latest version on [pub.dev](https://pub.dev/packages/riverpod_infinite_scroll/versions).  
Also, I see the library's version after the change is the same `1.0.9`: https://github.com/ftognetto/riverpod_infinite_scroll/blob/main/pubspec.yaml#L5

Should version `1.0.10` be published on [pub.dev](https://pub.dev/packages/riverpod_infinite_scroll/versions)?

**Comment by nader138** [comment]
@ftognetto please update the pubdev package to include #45  ! so far the package is broken and doesn't support Flutter 3.22!!

**Comment by ftognetto** [comment]
Sorry all, the pr has been published now!
https://pub.dev/packages/riverpod_infinite_scroll/versions/1.0.10
