### ISSUE TITLE
Support riverpod 2.0

### ISSUE THREAD

**Issue by manuel-escola** [quantosapplications/riverpod_infinite_scroll#7]
I am currently getting the following error in my project:

Because every version of riverpod_infinite_scroll depends on flutter_riverpod ^1.0.3 and my_app depends on flutter_riverpod ^2.0.0-dev.9, riverpod_infinite_scroll is forbidden.

Can version 2 (preview) also be supported?

**Comment by ftognetto** [comment]
HI @manuel-escola i was waiting that version 2 comes to stable before upgrading...
In the meanwhile you can override dependency or fork the repo.
I will leave this open until version 2 will be released in stable.

Thank you!

**Comment by manuel-escola** [comment]
Thank you for your quick answer. I did so :)
Thanks for the effort you put into building this amazing extension.

**Comment by ftognetto** [comment]
Hi @manuel-escola we have finally reached riverpod version 2! the package is already updated in pub.dev.
Thank you :)
