### ISSUE TITLE
Attempting to freeze 

### ISSUE THREAD

**Issue by h-unterp** [quantosapplications/riverpod_infinite_scroll#8]
**NOTE**: This is not super important, I am just curious, feel free to close this "bug", response would be appreciated, thank you.
I can start to see why you did not use freezed in https://github.com/quantosapplications/riverpod_infinite_scroll/blob/main/lib/src/paged_state.dart

```dart
  PagedState<PageKeyType, ItemType> copyWith(
      {List<ItemType>? records,
      dynamic error,
      dynamic nextPageKey = undefined,
```

Attempted to Freeze `PageKeyType` and `ItemType` from https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/lib/src/core/paging_controller.dart

Like so:

```dart
@freezed
class PagedState<PageKeyType, ItemType> with _$PagedState {
  const factory PagedState({
    @Default([]) List<ItemType>? records,
    @Default([]) List<PageKeyType> previousPageKeys,
```

In the following project that I forked: https://github.com/hunterpp/riverpod_infinite_scroll/blob/37884af6a7b8139c10446580bb172b50b93f050d/lib/src/paged_state.dart#L9

However it errors with: 

![Screen Shot 2022-06-23 at 11 00 18 AM](https://user-images.githubusercontent.com/772917/175359791-9830bf6e-7492-4168-aa8f-8d019fa1da1f.png)

And I'm pretty flummoxed. Any ideas how to freeze it? This is not super important, I am just curious, feel free to close this "bug", response would be appreciated, thank you.

**Comment by ftognetto** [comment]
Hi, this is a nice question!
Honestly now I don't remember why I did a custom implementation of the class without using freezed.
It certainly had to do with the fact that freezed found a (genius) way of distinguishing between the concept of a null parameter and a parameter not passed to the copyWith method.
On the other hand, in a standard implementation of the copyWith (`value ?? this.value`) method, if we pass a null value, the result is not to change the value of the variable, making it somehow non-nullable.
So I probably wanted to emphasize this for some variable ... Although this is strange to me especially for the error variable (in my implementation it becomes non-nullable).
Give me some time to investigate and give you a more precise answer.

**Comment by ftognetto** [comment]
Anyway I tried to convert PagingState to a freezed class without errors


```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'paged_state.freezed.dart';


@freezed
class PagedState<PageKeyType, ItemType> with _$PagedState {
  const factory PagedState({
    List<ItemType>? records,
    dynamic error,
    PageKeyType? nextPageKey,
    @Default([]) List<PageKeyType> previousPageKeys
  }) = _PagedState;

}
```

**Comment by ftognetto** [comment]
Hi, I'm still working on it. At the moment I found no reason why the PagedState shouldn't be freezed

**Comment by h-unterp** [comment]
Maybe related to https://github.com/rrousselGit/freezed/issues/464 ?

**Comment by ftognetto** [comment]
Hi @hunterpp exactly! I was looking inside a big project in which I use riverpod_infinite_scroll and I often extend the PagedState class to add properties I need.

So if I had freezed PagedState it would be impossibile for others to extends it and customize accordingly their needs.

Thanks for pointing this out, I will comment the class so that other could understand why

**Comment by h-unterp** [comment]
Yes, I am doing quite sophisticated inheritance like so: https://github.com/hunterpp/riverpod_child_provider/blob/main/lib/dogs.dart
