### ISSUE TITLE
Need to import infinite_scroll_pagination for PagedListView

### ISSUE THREAD

**Issue by h-unterp** [quantosapplications/riverpod_infinite_scroll#9]
It was not covered in documentation to import PagedListView from https://pub.dev/packages/infinite_scroll_pagination

Either:
1. Document this.
or
3. include if possible https://pub.dev/packages/infinite_scroll_pagination in riverpod_infinite_scroll

**Comment by ftognetto** [comment]
Currently infinite_scroll_pagination is already a dependency of riverpod_infinite_scroll, but if you want to use a infinite_scroll_pagination widget in your ui you must import it :)

**Comment by ftognetto** [comment]
Thanks to you now this is on the documentation :)
